---
title: "R package development"
subtitle: "from laying functions to package hatching"
author: "Maëlle Salmon "
date: "2018/03/16"
output:
  xaringan::moon_reader:
    lib_dir: libs
    nature:
      highlightStyle: github
      highlightLines: true
      countIncrementalSlides: false
---


```{r setup, include=FALSE}
options(htmltools.dir.version = FALSE)
```

## Good morning! Goeie môre! Sanibonani! Molweni! Bonjour!

What I do in R...

* (Research) software engineer for rOpenSci & Locke Data.

* R-Ladies, R Weekly.

* Onboarding co-editor at rOpenSci.


---

## Why learning about package development?

Jon Calder's very good wording, thanks Jon!

--

* To share code (and data)

--

* To leverage existing tooling

--

* To contribute to other packages


---

## Automation!

<blockquote class="twitter-tweet" data-lang="ca"><p lang="en" dir="ltr">The usethis package implements this important principle: Automate that which can be automated. Your computer was literally born to implement rote-but-fussy stuff for you. <a href="https://t.co/OfIUzSBlc7">https://t.co/OfIUzSBlc7</a></p>&mdash; Jenny Bryan (@JennyBryan) <a href="https://twitter.com/JennyBryan/status/935562495816753153?ref_src=twsrc%5Etfw">28 de novembre de 2017</a></blockquote>

--

* `RStudio`

* `devtools` and `usethis`

* `roxygen2`


---
## Today's workshop

--

* Hands-on! Is every laptop ready?

--

* These slides, hands-on, then a few slides again.

--

* Ask and help us help you!

--

* You should go home knowing the basics and how to go further.

---
## Today's package

`someone`, create fake people.

* Inspired by [`charlatan`](https://github.com/ropensci/charlatan), "create fake data in R".

* real baby names data from Stats SA.

---

## Let's go!

<iframe src="https://giphy.com/embed/XOvKIu18WbpgQ" width="480" height="480" frameBorder="0" class="giphy-embed" allowFullScreen></iframe><p><a href="https://giphy.com/gifs/XOvKIu18WbpgQ">via GIPHY</a></p>

---

## How to go further: your own package(s)?


My own blog post with many links to fantastic resources: ["How to develop good R packages"](http://www.masalmon.eu/2017/12/11/goodrpackages/)

---

## How to go further: your research compendii?

Research compendium = R package containing all the code (and data) incl. dependencies list, necessary to reproduce an article.


See [this thread for instance](https://github.com/ropensci/unconf17/issues/5).

---

## How to go further: contribute to other packages?

--

* rOpenSci onboarding (more on that tomorrow!) and [contributr Shiny app](https://github.com/LucyMcGowan/contributr).

--

*  Mara Averick's ["contributing to the tidyverse"](https://github.com/batpigandme/tverse_contributing/blob/master/tverse_contributing_rstudioconf_compressed.pdf) slides, [tidyverse contributing guide](https://www.tidyverse.org/contribute/), [Jim Hester's blog post "contributing code to the tidyverse"](http://www.jimhester.com/2017/08/08/contributing/).


---

## Last but not least, what about `someone`?

--

*  Ask more data from Stats SA?

--

*  Andrew Collier's [`saffeR`](https://github.com/DataWookie/saffeR), an R package aggregating a selection of things relating to South Africa. 


---

## See you tomorrow! Sien jou môre! Ngizokubona kusasa! Ndiza kubona ngomso!

<iframe src="https://giphy.com/embed/l4KibK3JwaVo0CjDO" width="480" height="474" frameBorder="0" class="giphy-embed" allowFullScreen></iframe><p><a href="https://giphy.com/gifs/afv-funny-fail-lol-l4KibK3JwaVo0CjDO">via GIPHY</a></p>


